version: '3.8'

services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo:/data/db
      - ./init/init.js:/docker-entrypoint-initdb.d/init.js